SELECT COUNT(*) FROM BORROWERS;
SELECT COUNT(*) FROM LOANS;
SELECT COUNT(*) FROM PROPERTIES;
SELECT COUNT(*) FROM PAYMENT_HISTORY;
SELECT COUNT(*) FROM ESCROW;
SELECT COUNT(*) FROM DELINQUENCY;
SELECT COUNT(*) FROM INVESTORS;
SELECT COUNT(*) FROM SERVICERS;