SELECT COUNT(*) AS BORROWERS_COUNT FROM CURATED.BORROWERS;
SELECT COUNT(*) AS LOANS_COUNT FROM CURATED.LOANS;
SELECT COUNT(*) AS PROPERTIES_COUNT FROM CURATED.PROPERTIES;
SELECT COUNT(*) AS PAYMENT_HISTORY_COUNT FROM CURATED.PAYMENT_HISTORY;
SELECT COUNT(*) AS ESCROW_COUNT FROM CURATED.ESCROW;
SELECT COUNT(*) AS DELINQUENCY_COUNT FROM CURATED.DELINQUENCY;
SELECT COUNT(*) AS INVESTORS_COUNT FROM CURATED.INVESTORS;
SELECT COUNT(*) AS SERVICERS_COUNT FROM CURATED.SERVICERS;