USE DATABASE MORTGAGE_SERVICING_AI;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
NULL_IF=('NULL','');
