USE DATABASE MORTGAGE_SERVICING_AI;
USE SCHEMA CURATED;
CREATE OR REPLACE TASK TASK_REFRESH_CURATED
WAREHOUSE=MORTGAGE_WH
SCHEDULE='USING CRON 0 * * * * UTC'
AS
INSERT OVERWRITE INTO CURATED.LOANS SELECT * FROM RAW.LOANS;