USE DATABASE MORTGAGE_SERVICING_AI;
USE SCHEMA ANALYTICS;
CREATE OR REPLACE TASK TASK_REFRESH_ANALYTICS
WAREHOUSE=MORTGAGE_WH
AFTER CURATED.TASK_REFRESH_CURATED
AS
CREATE OR REPLACE TABLE LOAN_PORTFOLIO_CACHE AS
SELECT * FROM VW_LOAN_PORTFOLIO;