USE SCHEMA RAW;
CREATE OR REPLACE TABLE BORROWERS(
BORROWER_ID VARCHAR,
FIRST_NAME VARCHAR,
LAST_NAME VARCHAR,
DOB DATE,
SSN_LAST4 VARCHAR,
PHONE VARCHAR,
EMAIL VARCHAR,
ANNUAL_INCOME NUMBER(12,2),
EMPLOYMENT_STATUS VARCHAR,
CREDIT_SCORE NUMBER,
DEBT_TO_INCOME NUMBER(5,2),
STATE VARCHAR,
CITY VARCHAR,
ZIP_CODE VARCHAR
);