USE SCHEMA RAW;
CREATE OR REPLACE TABLE LOANS(
LOAN_ID VARCHAR,
BORROWER_ID VARCHAR,
PROPERTY_ID VARCHAR,
INVESTOR_ID VARCHAR,
SERVICER_ID VARCHAR,
LOAN_AMOUNT NUMBER(12,2),
CURRENT_UPB NUMBER(12,2),
INTEREST_RATE NUMBER(5,2),
LOAN_STATUS VARCHAR,
LTV NUMBER(5,2),
ORIGINATION_DATE DATE
);