USE SCHEMA RAW;
CREATE OR REPLACE TABLE PAYMENT_HISTORY(
PAYMENT_ID VARCHAR,
LOAN_ID VARCHAR,
PAYMENT_DATE DATE,
PAYMENT_AMOUNT NUMBER(12,2),
PRINCIPAL_PAID NUMBER(12,2),
INTEREST_PAID NUMBER(12,2),
STATUS VARCHAR
);